[package]
name = "lavarand"
version = "0.1.0"
edition = "2024"

[dependencies]
fast_image_resize = { version = "6.0.0", features = ["image"] }
hex = "0.4.3"
hex-literal = "1.1.0"
image = "0.25.9"
num-bigint = "0.4.6"
num-traits = "0.2.19"
sha1 = "0.10.6"
sha2 = "0.10.9"
